### ISSUE TITLE
API設計

### ISSUE THREAD

**Issue by naosuke884** [2024-vol11-18/hands-free-cooking#1]

**Comment by hareiharei** [comment]
とりあえず成功の場合のみ定義
- GET /search/{search_word}
- GET /recipe/{id}
- POST /message
https://app.swaggerhub.com/apis/harei.shirao/hands-free-cooking/1.0.0

**Comment by hareiharei** [comment]
-[] 成功の場合のAPI定義
-[] 失敗の場合のAPI定義
