### ISSUE TITLE
ハンズフリーモードの画面の作成

### ISSUE THREAD

**Issue by naosuke884** [2024-vol11-18/hands-free-cooking#7]
レシピを作成開始〜終了までの画面

**Comment by hareiharei** [comment]
- [ ] ページのルーティング
- [ ] レシピ読み上げ時のコンポーネントの基本的なHTMLの部分だけ作る
- [ ] タイマーのコンポーネントの基本的なHTMLの部分だけ作る
- [ ] ローディング時のコンポーネントの基本的なHTMLの部分だけ作る
- [ ] コンポーネントの遷移
- [ ] UIを整える
